version: 0.2

env:
  parameter-store:
    DOCKER_USERNAME: "/dockerhub/username"
    DOCKER_PASSWORD: "/dockerhub/password"

phases:
  pre_build:
    commands:
      - echo Logging in to Gitea Docker registry...
      - docker login giteaserver.spacetechnology.net -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t giteaserver.spacetechnology.net/egsundqvist/imagebook-userapi:latest .
  post_build:
    commands:
      - echo Pushing the Docker image to Gitea Docker registry...
      - docker push giteaserver.spacetechnology.net/egsundqvist/imagebook-userapi:latest
