version: 0.2

env:
  parameter-store:
    DOCKERHUB_USERNAME: "/dockerhub/username"
    DOCKERHUB_PASSWORD: "/dockerhub/password"

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t egsundqvist/imagebook-userapi:latest .
  post_build:
    commands:
      - echo Pushing the Docker image to Docker Hub...
      - docker push egsundqvist/imagebook-userapi:latest
