Development:
  SQLALCHEMY_DATABASE_URI: ""
  JWT_SECRET_KEY_FRONTEND: ""
  JWT_SECRET_KEY_BACKEND: ""
  IMAGEAPI_URL: ""
  ALLOWED_EMAILS: ""

Production:
  SQLALCHEMY_DATABASE_URI: ""
  JWT_SECRET_KEY_FRONTEND: ""
  JWT_SECRET_KEY_BACKEND: ""
  IMAGEAPI_URL: ""
  ALLOWED_EMAILS: ""
